EauClairesSalon/Models/Clients.cs
using System;

namespace EauClairesSalon.Models
{
  public class Client
  {
    public int ClientId { get; set; }
    public string Name { get; set; }
    public  string  CurlinessType { get;}
    public  string  StrandsType { get; set;}
    public  string VolumeType { get; set; }
    public int ContactNum { get; set; }
    public int StylistId { get; set; }
    public virtual Stylist Stylist { get; set; }






}
}

EauClairesSalon/Models/EauClairesSalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace EauClairesSalon.Models
{
  public class EauClairesSalonContext : DbContext
  {
    public virtual DbSet<Stylist> Stylists { get; set; }
    public DbSet<Client> Clients { get; set; }

    public EauClairesSalonContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

EauClairesSalon/Models/Stylists.cs
using System;
using System.Collections.Generic;

namespace EauClairesSalon.Models
{
  public class Stylist
  {
    public Stylist()
    {
      this.Clients = new HashSet<Client>();
    }

    public int StylistId { get; set; }
    public string Name { get; set; }
    public DateTime EmploymentDate { get; set; }
    public int ContactNum { get; set; }
    public string Schedule { get; set; }


    public virtual ICollection<Client> Clients { get; set; }
  }
}

EauClairesSalon/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using EauClairesSalon.Models;
using System.Collections.Generic;
using System.Linq;

namespace EauClairesSalon.Controllers
{
  public class ClientsController : Controller
  {
    private readonly EauClairesSalonContext _db;

    public ClientsController(EauClairesSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Client> model = _db.Clients.Include(client => client.Stylist).ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Client client)
    {
      _db.Clients.Add(client);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      return View(thisClient);
    }

    public ActionResult Edit(int id)
    {
      var thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View(thisClient);
    }

    [HttpPost]
    public ActionResult Edit(Client client)
    {
      _db.Entry(client).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      return View(thisClient);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
      _db.Clients.Remove(thisClient);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

EauClairesSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace EauClairesSalon.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }

    }
}

EauClairesSalon/Controllers/ItemsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using EauClairesSalon.Models;
using System.Collections.Generic;
using System.Linq;

namespace EauClairesSalon.Controllers
{
  public class ItemsController : Controller
  {
    private readonly EauClairesSalonContext _db;

    public ItemsController(EauClairesSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Item> model = _db.Items.Include(item => item.Category).ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.CategoryId = new SelectList(_db.Categories, "CategoryId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Item item)
    {
      _db.Items.Add(item);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Item thisItem = _db.Items.FirstOrDefault(item => item.ItemId == id);
      return View(thisItem);
    }

    public ActionResult Edit(int id)
    {
      var thisItem = _db.Items.FirstOrDefault(item => item.ItemId == id);
      ViewBag.CategoryId = new SelectList(_db.Categories, "CategoryId", "Name");
      return View(thisItem);
    }

    [HttpPost]
    public ActionResult Edit(Item item)
    {
      _db.Entry(item).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisItem = _db.Items.FirstOrDefault(item => item.ItemId == id);
      return View(thisItem);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisItem = _db.Items.FirstOrDefault(item => item.ItemId == id);
      _db.Items.Remove(thisItem);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

EauClairesSalon/Controllers/StylistsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using EauClairesSalon.Models;
using System.Collections.Generic;
using System.Linq;

namespace EauClairesSalon.Controllers
{
  public class StylistsController : Controller
  {
    private readonly EauClairesSalonContext _db;

    public StylistsController(EauClairesSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Stylist> model = _db.Stylists.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Stylist stylist)
    {
      _db.Stylists.Add(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }
    public ActionResult Edit(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost]
    public ActionResult Edit(Stylist stylist)
    {
      _db.Entry(stylist).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      _db.Stylists.Remove(thisStylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

EauClairesSalon/Views/Categories/Create.cshtml
@{
  Layout = "_Layout";
}

@model EauClairesSalon.Models.Category

<h4>Add a new task</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <input type="submit" value="Add new category" />
}
<p>@Html.ActionLink("Show all categories", "Index")</p>

EauClairesSalon/Views/Categories/Delete.cshtml
@{
  Layout = "_Layout";
}

@model EauClairesSalon.Models.Category

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

EauClairesSalon/Views/Categories/Edit.cshtml
@{
  Layout = "_Layout";
}

@model EauClairesSalon.Models.Category

<h2>Edit</h2>

<h4>Edit this category: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.CategoryId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

EauClairesSalon/Views/Categories/Index.cshtml
@{
  Layout = "_Layout";
}

@using EauClairesSalon.Models;

<h1>Categories</h1>

@if (@Model.Count == 0)
{
  <h3>No categories have been added yet!</h3>
} 

<ul>
  @foreach(Category category in Model)
  {
    <li>@Html.ActionLink($"{category.Name}", "Details", new { id = category.CategoryId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new category", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

EauClairesSalon/Views/Client/Create.cshtml
@{
  Layout = "_Layout";
}

@model EauClairesSalon.Models.Client
<main class="container">
  <h4>Add a new client</h4>
  @using (Html.BeginForm())
  {
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)

    @Html.DropDownList("CurlinessType", new List<SelectListItem>
  {
  new SelectListItem { Text = "unknown", Value = "unknown", Selected=true},
  new SelectListItem { Text = "1a: Stick-straight.", Value = "1a: Stick-straight."},
  new SelectListItem { Text = "1b: Straight but with a slight body wave adding some volume.", Value = "1b: Straight but with a slight body wave adding some volume."},
  new SelectListItem { Text = "1c: Straight with body wave and one or two visible S-waves.", Value = "1c: Straight with body wave and one or two visible S-waves."},

  new SelectListItem { Text = "2a: Loose with stretched S-waves throughout.", Value = "2a: Loose with stretched S-waves throughout."},
  new SelectListItem { Text = "2b: Shorter with more distinct S-waves.", Value = "2b: Shorter with more distinct S-waves."},
  new SelectListItem { Text = "2c: Distinct S-waves, some spiral curling.", Value = "2c: Distinct S-waves, some spiral curling."},

  new SelectListItem { Text = "3a: Big, loose spiral curls.", Value = "3a: Big, loose spiral curls."},
  new SelectListItem { Text = "3b: Bouncy ringlets.", Value = "3b: Bouncy ringlets."},
  new SelectListItem { Text = "3c: Tight corkscrews.", Value = "3c: Tight corkscrews."},

  new SelectListItem { Text = "4a: Tightly coiled S-curls.", Value = "4a: Tightly coiled S-curls."},
  new SelectListItem { Text = "4b: Z-patterned", Value = "4b: Z-patterned"},
  new SelectListItem { Text = "4c: Mostly Z-patterned", Value = "4c: Mostly Z-patterned"}
  }, "Select Curliness Type")

    @Html.DropDownList("StrandsType", new List<SelectListItem>
  {
  new SelectListItem { Text = "unknown", Value = "unknown", Selected=true},
  new SelectListItem { Text = "F: Fine", Value = "F: Fine"},
  new SelectListItem { Text = "M: Medium", Value = "M: Medium"},
  new SelectListItem { Text = "C: Coarse", Value = "C: Coarse"}
  }, "Select Strand Type")

    @Html.DropDownList("VolumeType", new List<SelectListItem>
  {
  new SelectListItem { Text = "unknown", Value = "unknown", Selected=true},
  new SelectListItem { Text = "i: Thin", Value = "i: Thin"},
  new SelectListItem { Text = "ii: Normal", Value = "ii: Normal"},
  new SelectListItem { Text = "iii: Thick", Value = "iii: Thick"}
  }, "Select Volume Type")


    @Html.LabelFor(model => model.ContactNum)
    @Html.TextBoxFor(model => model.ContactNum)

    @Html.LabelFor(model => model.Stylist)
    @Html.DropDownList("StylistId")

    <button type="submit" value="Add new Client" class="btn btn-dark" />
  }
  <p>@Html.ActionLink("Show all Clients", "Index")</p>
</main>

EauClairesSalon/Views/Clients/Create.cshtml
@{
  Layout = "_Layout";
}

@model EauClairesSalon.Models.Client
<main class="container">
  <h4>Add a new client</h4>
  @using (Html.BeginForm())
  {
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name,
  new { required="required" })

    @Html.DropDownList("CurlinessType", new List<SelectListItem>
  {
  new SelectListItem { Text = "unknown", Value = "unknown", Selected=true},
  new SelectListItem { Text = "1a: Stick-straight.", Value = "1a: Stick-straight."},
  new SelectListItem { Text = "1b: Straight but with a slight body wave adding some volume.", Value = "1b: Straight but with a slight body wave adding some volume."},
  new SelectListItem { Text = "1c: Straight with body wave and one or two visible S-waves.", Value = "1c: Straight with body wave and one or two visible S-waves."},

  new SelectListItem { Text = "2a: Loose with stretched S-waves throughout.", Value = "2a: Loose with stretched S-waves throughout."},
  new SelectListItem { Text = "2b: Shorter with more distinct S-waves.", Value = "2b: Shorter with more distinct S-waves."},
  new SelectListItem { Text = "2c: Distinct S-waves, some spiral curling.", Value = "2c: Distinct S-waves, some spiral curling."},

  new SelectListItem { Text = "3a: Big, loose spiral curls.", Value = "3a: Big, loose spiral curls."},
  new SelectListItem { Text = "3b: Bouncy ringlets.", Value = "3b: Bouncy ringlets."},
  new SelectListItem { Text = "3c: Tight corkscrews.", Value = "3c: Tight corkscrews."},

  new SelectListItem { Text = "4a: Tightly coiled S-curls.", Value = "4a: Tightly coiled S-curls."},
  new SelectListItem { Text = "4b: Z-patterned", Value = "4b: Z-patterned"},
  new SelectListItem { Text = "4c: Mostly Z-patterned", Value = "4c: Mostly Z-patterned"}
  }, "Select Curliness Type")

    @Html.DropDownList("StrandsType", new List<SelectListItem>
  {
  new SelectListItem { Text = "unknown", Value = "unknown", Selected=true},
  new SelectListItem { Text = "F: Fine", Value = "F: Fine"},
  new SelectListItem { Text = "M: Medium", Value = "M: Medium"},
  new SelectListItem { Text = "C: Coarse", Value = "C: Coarse"}
  }, "Select Strand Type")

    @Html.DropDownList("VolumeType", new List<SelectListItem>
  {
  new SelectListItem { Text = "unknown", Value = "unknown", Selected=true},
  new SelectListItem { Text = "i: Thin", Value = "i: Thin"},
  new SelectListItem { Text = "ii: Normal", Value = "ii: Normal"},
  new SelectListItem { Text = "iii: Thick", Value = "iii: Thick"}
  }, "Select Volume Type")


    @Html.LabelFor(model => model.ContactNum)
    @Html.TextBoxFor(model => model.ContactNum,
  new { required="required" })

    @Html.LabelFor(model => model.Stylist)
    @Html.DropDownList("StylistId")

    <button href='@Url.Action("Index", "Clients")' type="submit" value="Add new Client" class="btn btn-dark" >Add new client</button>
  }
</main>

EauClairesSalon/Views/Clients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model EauClairesSalon.Models.Client
<main class="container">
  <h2>Are you sure you want to delete this?</h2>

  @Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
  @using (Html.BeginForm())
  {
    <input type="submit" value="Delete" />
  }
  @Html.ActionLink("Back to Vendor", "Index")
</main>

EauClairesSalon/Views/Clients/Details.cshtml
@{
  Layout = "_Layout";
}

@model EauClairesSalon.Models.Client
<main class="container">
  <h2>Client Details</h2>
  <hr />
  <h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>
      <p>@Html.ActionLink("Edit Client", "Edit", new { id = Model.ClientId })</p>
      <p>@Html.ActionLink("Delete Client", "Delete", new { id = Model.ClientId })</p>
      <p>@Html.ActionLink("Back to list", "Index")</p>
</main>

EauClairesSalon/Views/Clients/Edit.cshtml
@{
  Layout = "_Layout";
}

@model EauClairesSalon.Models.Client
<main class="container">
<h2>Edit</h2>

<h4>Edit this Client: @Html.DisplayFor(model => model.Name)</h4>

  @using (Html.BeginForm())
  {
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name,
  new { required="required" })

    @Html.DropDownList("CurlinessType", new List<SelectListItem>
  {
  new SelectListItem { Text = "Unknown Curliness type", Value = "unknown", Selected=true},
  new SelectListItem { Text = "1a: Stick-straight.", Value = "1a: Stick-straight."},
  new SelectListItem { Text = "1b: Straight but with a slight body wave adding some volume.", Value = "1b: Straight but with a slight body wave adding some volume."},
  new SelectListItem { Text = "1c: Straight with body wave and one or two visible S-waves.", Value = "1c: Straight with body wave and one or two visible S-waves."},

  new SelectListItem { Text = "2a: Loose with stretched S-waves throughout.", Value = "2a: Loose with stretched S-waves throughout."},
  new SelectListItem { Text = "2b: Shorter with more distinct S-waves.", Value = "2b: Shorter with more distinct S-waves."},
  new SelectListItem { Text = "2c: Distinct S-waves, some spiral curling.", Value = "2c: Distinct S-waves, some spiral curling."},

  new SelectListItem { Text = "3a: Big, loose spiral curls.", Value = "3a: Big, loose spiral curls."},
  new SelectListItem { Text = "3b: Bouncy ringlets.", Value = "3b: Bouncy ringlets."},
  new SelectListItem { Text = "3c: Tight corkscrews.", Value = "3c: Tight corkscrews."},

  new SelectListItem { Text = "4a: Tightly coiled S-curls.", Value = "4a: Tightly coiled S-curls."},
  new SelectListItem { Text = "4b: Z-patterned", Value = "4b: Z-patterned"},
  new SelectListItem { Text = "4c: Mostly Z-patterned", Value = "4c: Mostly Z-patterned"}
  }, "Select Curliness Type")

    @Html.DropDownList("StrandsType", new List<SelectListItem>
  {
  new SelectListItem { Text = "Unknown Strand Type", Value = "unknown", Selected=true},
  new SelectListItem { Text = "F: Fine", Value = "F: Fine"},
  new SelectListItem { Text = "M: Medium", Value = "M: Medium"},
  new SelectListItem { Text = "C: Coarse", Value = "C: Coarse"}
  }, "Select Strand Type")

    @Html.DropDownList("VolumeType", new List<SelectListItem>
  {
  new SelectListItem { Text = "Unknown Strand Type", Value = "unknown", Selected=true},
  new SelectListItem { Text = "i: Thin", Value = "i: Thin"},
  new SelectListItem { Text = "ii: Normal", Value = "ii: Normal"},
  new SelectListItem { Text = "iii: Thick", Value = "iii: Thick"}
  }, "Select Volume Type")


    @Html.LabelFor(model => model.ContactNum)
    @Html.TextBoxFor(model => model.ContactNum,
  new { required="required" })

    @Html.LabelFor(model => model.Stylist)
    @Html.DropDownList("StylistId")

    <button href='@Url.Action("Index", "Clients")' type="submit" value="Edit Client" class="btn btn-dark" >Save Edited Client</button>
  }

<p>@Html.ActionLink("Back to list", "Index")</p>
</main>

EauClairesSalon/Views/Clients/Index.cshtml
@{
  Layout = "_Layout";
}

@using EauClairesSalon.Models;
@model List<EauClairesSalon.Models.Client>;
<main class="container">
  <h1>Clients</h1>

  @if (@Model.Count == 0)
  {
    <h3>No clients have been added yet!</h3>
  }

  @foreach (Client client in Model)
  {
    <li>@Html.ActionLink($"{client.Name}", "Details", new { id = client.ClientId }) | @client.Stylist.Name</li>
  }

  <p>@Html.ActionLink("Add new client", "Create")</p>
</main>

EauClairesSalon/Views/Items/Delete.cshtml
@{
  Layout = "_Layout";
}

@model EauClairesSalon.Models.Item

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

EauClairesSalon/Views/Items/DeleteAll.cshtml
@{
  Layout = "_Layout";
}

<h1>Your list has been cleared!</h1>
<p><a href="/items">Back to list.</a></p>

EauClairesSalon/Views/Items/Edit.cshtml
@{
  Layout = "_Layout";
}

@model EauClairesSalon.Models.Item

<h2>Edit</h2>

<h4>Edit this task: @Html.DisplayFor(model => model.Description)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.ItemId)

  @Html.LabelFor(model => model.Description)
  @Html.EditorFor(model => model.Description)

  @Html.LabelFor(model => model.Category)
  @Html.DropDownList("CategoryId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

EauClairesSalon/Views/Stylists/Create.cshtml
@{
  Layout = "_Layout";
}

@model EauClairesSalon.Models.Stylist
<main class="container">
  <h4>Add a new task</h4>
  @using (Html.BeginForm())
  {
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)

    @Html.LabelFor(model => model.EmploymentDate)
    @Html.TextBoxFor(model => model.EmploymentDate,
  new { @type = "date" , @value = DateTime.Now })

    @Html.LabelFor(model => model.ContactNum)
    @Html.TextBoxFor(model => model.ContactNum)

    @Html.LabelFor(model => model.Schedule)
    @Html.TextBoxFor(model => model.Schedule)

    <input type="submit" value="Add new stylist" class="btn btn-dark" />
  }
  <p>@Html.ActionLink("Show all stylists", "Index")</p>
</main>

EauClairesSalon/Views/Stylists/Delete.cshtml
@{
  Layout = "_Layout";
}

@model EauClairesSalon.Models.Stylist

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

EauClairesSalon/Views/Stylists/Details.cshtml
@{
  Layout = "_Layout";
}

@model EauClairesSalon.Models.Stylist
<main class="container">
  <h2>Stylist Details</h2>
  <hr />
  <h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
  <p>@Html.ActionLink("Edit Stylist", "Edit", new { id = Model.StylistId})</p>
  <p>@Html.ActionLink("Delete Stylist", "Delete", new { id = Model.StylistId})</p>
  <p>@Html.ActionLink("Back to list", "Index")</p>

  <button href='@Url.Action("Edit", "Stylists" , new { id = Model.StylistId})' type="button" class="btn btn-dark">Edit
    Stylist</button>
</main>

EauClairesSalon/Views/Stylists/Index.cshtml
@{
  Layout = "_Layout";
}

@using EauClairesSalon.Models;
<main class="container">
  <h1>Eau Claire's Stylists</h1>

  @if (@Model.Count == 0)
  {
    <h3>No categories have been added yet!</h3>
  }

  <ul>
    @foreach (Stylist stylist in Model)
    {
      <li>@Html.ActionLink($"{stylist.Name}", "Details", new { id = stylist.StylistId })</li>
    }
  </ul>

  <p>@Html.ActionLink("Add new stylist", "Create")</p>
  <p>@Html.ActionLink("Home", "Index", "Home")</p>
</main>